# Generated by Django 4.1.6 on 2023-02-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="session_note",
            field=models.CharField(max_length=100),
        ),
    ]
