# Generated by Django 4.1.6 on 2023-02-22 00:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_session_session_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_open_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date opened"
            ),
        ),
    ]
